export default  
[
  {
    name: 'T5_COMUNICACION_DE_DATOS_2CM42_HERNANDEZ_VILLALOBOS_JUAN',
    url: '/Files/T5_COMUNICACION_DE_DATOS_2CM42_HERNANDEZ_VILLALOBOS_JUAN.pdf'
  },
  {
    name: 'T5_COMUNICACION_DE_DATOS_2CM42_HERNANDEZ_VILLALOBOS_JUAN',
    url: '/Files/T5_COMUNICACION_DE_DATOS_2CM42_HERNANDEZ_VILLALOBOS_JUAN.pdf'
  }
]